import type { Post, RankedAgency } from './types'

function agency(
  rank: number,
  name: string,
  tagline: string,
  location: string,
  founded: string,
  rating: number,
  bestFor: string,
  highlights: string[],
): RankedAgency {
  return {
    rank,
    name,
    tagline,
    location,
    founded,
    rating,
    bestFor,
    highlights,
    website: 'https://example.com',
  }
}

const intro = (sector: string, plural: string): Post['body'] => [
  {
    type: 'paragraph',
    text: `Choosing the right ${sector} partner can be the difference between predictable growth and wasted budget. Our editorial team independently reviews ${plural} every quarter, scoring each one against a consistent methodology so you can shortlist with confidence.`,
  },
  {
    type: 'heading',
    text: 'How we ranked these agencies',
    id: 'methodology',
  },
  {
    type: 'paragraph',
    text: 'Every agency on this list was assessed across five weighted criteria. We do not accept payment for placement — rankings reflect verifiable outcomes, client feedback and the depth of each team’s expertise.',
  },
  {
    type: 'list',
    items: [
      'Proven results and case studies with measurable outcomes',
      'Client retention and satisfaction signals',
      'Depth of specialist expertise and team experience',
      'Transparency around pricing, reporting and process',
      'Reputation, awards and verified third-party reviews',
    ],
  },
  {
    type: 'heading',
    text: `The best ${sector} agencies`,
    id: 'rankings',
  },
  {
    type: 'agencies',
    intro: `Here are our top-rated ${plural}, ranked from one to ten. Each entry includes who they’re best suited to and what makes them stand out.`,
  },
  {
    type: 'heading',
    text: `How to choose the right ${sector} agency`,
    id: 'how-to-choose',
  },
  {
    type: 'paragraph',
    text: 'Start with clarity on your goals and budget, then shortlist three to five agencies that specialise in your sector. Ask for relevant case studies, speak to references, and make sure reporting is transparent before you commit.',
  },
  {
    type: 'subheading',
    text: 'Questions to ask before signing',
    id: 'questions',
  },
  {
    type: 'ordered',
    items: [
      'What results have you achieved for clients like us?',
      'Who will actually work on our account day to day?',
      'How do you measure and report on success?',
      'What does the onboarding process look like?',
      'What are the contract terms and notice periods?',
    ],
  },
  {
    type: 'quote',
    text: 'The best agency relationships are partnerships, not transactions. Look for a team that asks sharp questions about your business before they pitch a solution.',
    cite: 'Best Agencies Editorial',
  },
  {
    type: 'heading',
    text: 'Final verdict',
    id: 'verdict',
  },
  {
    type: 'paragraph',
    text: 'Any agency on this list is a strong, vetted choice. The right fit depends on your sector, budget and the outcomes that matter most to you. Use our rankings as a shortlist, then trust the conversations to find your match.',
  },
]

export const posts: Post[] = [
  {
    slug: 'best-seo-agencies',
    title: 'Top 10 Best SEO Agencies in 2026',
    excerpt:
      'The SEO agencies driving real organic growth this year — independently ranked for technical expertise, content and link-building results.',
    category: 'digital-marketing',
    author: 'marcus-bell',
    publishedAt: '2026-01-14',
    updatedAt: '2026-05-02',
    readingTime: 11,
    image: '/images/post-seo.webp',
    imageAlt:
      'Analyst reviewing organic search performance dashboards on a laptop',
    tags: ['SEO', 'Organic Growth', 'Search', 'Rankings'],
    featured: true,
    trending: true,
    agencies: [
      agency(1, 'Northbeam Search', 'Technical SEO at enterprise scale', 'London, UK', '2014', 4.9, 'Enterprise & SaaS', ['Dedicated technical SEO squad', 'Proprietary crawl tooling', 'Transparent monthly reporting']),
      agency(2, 'Verdant Digital', 'Content-led organic growth', 'Manchester, UK', '2016', 4.8, 'Content & E-commerce', ['Editorial content studio', 'Strong retail track record', 'Topic-cluster strategy']),
      agency(3, 'Linkforge', 'Authority and digital PR', 'Bristol, UK', '2015', 4.8, 'Link Building', ['Earned national coverage', 'White-hat outreach', 'Data-led campaigns']),
      agency(4, 'Apex Organic', 'Local & multi-location SEO', 'Leeds, UK', '2017', 4.7, 'Local & Franchise', ['Local pack specialists', 'Reputation management', 'Scalable for chains']),
      agency(5, 'Summit SEO', 'Performance-driven search', 'Birmingham, UK', '2013', 4.7, 'Lead Generation', ['Conversion-focused', 'Clear KPIs', 'Senior-led accounts']),
      agency(6, 'Clarity Search', 'SEO for regulated industries', 'Edinburgh, UK', '2018', 4.6, 'Finance & Healthcare', ['Compliance-aware content', 'E-E-A-T expertise', 'Risk-managed strategy']),
      agency(7, 'Beacon Digital', 'International & multilingual SEO', 'London, UK', '2012', 4.6, 'Global Brands', ['hreflang specialists', '20+ markets', 'In-house translators']),
      agency(8, 'Pinnacle Growth', 'Startup-friendly SEO', 'Remote, UK', '2019', 4.5, 'Startups & Scaleups', ['Flexible retainers', 'Fast onboarding', 'Founder-friendly']),
      agency(9, 'Orbit Media Lab', 'Programmatic & data SEO', 'Cambridge, UK', '2017', 4.5, 'Marketplaces', ['Programmatic pages', 'Strong dev team', 'Scalable architecture']),
      agency(10, 'Evergreen Reach', 'Sustainable long-term SEO', 'Glasgow, UK', '2015', 4.4, 'SMEs', ['No long contracts', 'Education-first', 'Great communication']),
    ],
    body: intro('SEO', 'SEO agencies'),
  },
  {
    slug: 'best-web-design-agencies',
    title: 'Top 10 Best Web Design Agencies in 2026',
    excerpt:
      'From brand-defining redesigns to high-converting landing pages, these are the web design agencies setting the standard this year.',
    category: 'graphics-design',
    author: 'priya-nair',
    publishedAt: '2026-02-03',
    updatedAt: '2026-05-10',
    readingTime: 10,
    image: '/images/post-web-design.webp',
    imageAlt: 'Designer working on a website layout with colour swatches',
    tags: ['Web Design', 'UX', 'Branding', 'Conversion'],
    featured: true,
    trending: true,
    agencies: [
      agency(1, 'Studio Meridian', 'Design-led digital experiences', 'London, UK', '2011', 4.9, 'Brand & Product', ['Award-winning portfolio', 'Strategy to launch', 'Design systems experts']),
      agency(2, 'Form & Function', 'Conversion-focused design', 'Manchester, UK', '2015', 4.8, 'E-commerce', ['CRO specialists', 'Shopify Plus partners', 'A/B testing built in']),
      agency(3, 'Pixel & Pine', 'Beautiful, accessible websites', 'Bristol, UK', '2016', 4.8, 'Accessibility', ['WCAG AA standard', 'Inclusive design', 'Performance-obsessed']),
      agency(4, 'Northlight Studio', 'Editorial & content sites', 'Leeds, UK', '2014', 4.7, 'Publishers & Media', ['CMS specialists', 'Editorial UX', 'Fast Core Web Vitals']),
      agency(5, 'Kindling Creative', 'Brand identity & web', 'Brighton, UK', '2017', 4.7, 'Startups', ['Brand + web combined', 'Quick turnaround', 'Founder-friendly']),
      agency(6, 'Atlas Interactive', 'Enterprise web platforms', 'London, UK', '2010', 4.6, 'Enterprise', ['Headless builds', 'Scalable design systems', 'Global teams']),
      agency(7, 'Marlow Digital', 'High-converting landing pages', 'Reading, UK', '2018', 4.6, 'Performance', ['Landing page experts', 'Fast iteration', 'Paid media aligned']),
      agency(8, 'Cobalt & Co', 'SaaS product design', 'Cambridge, UK', '2016', 4.5, 'SaaS', ['Product design depth', 'Figma-first', 'UX research']),
      agency(9, 'Driftwood Studio', 'Hospitality & lifestyle', 'Cornwall, UK', '2015', 4.5, 'Hospitality', ['Visual storytelling', 'Booking integrations', 'Photography network']),
      agency(10, 'Bramble Web', 'Friendly small-business design', 'Remote, UK', '2019', 4.4, 'Small Business', ['Affordable packages', 'Care plans', 'Clear communication']),
    ],
    body: intro('web design', 'web design agencies'),
  },
  {
    slug: 'best-digital-marketing-agencies',
    title: 'Top 10 Best Digital Marketing Agencies in 2026',
    excerpt:
      'Full-funnel agencies that turn budget into measurable growth — ranked across paid media, SEO, email and social.',
    category: 'digital-marketing',
    author: 'marcus-bell',
    publishedAt: '2026-01-28',
    updatedAt: '2026-04-22',
    readingTime: 12,
    image: '/images/post-digital-marketing.webp',
    imageAlt: 'Marketing team reviewing campaign analytics on a large screen',
    tags: ['Digital Marketing', 'Paid Media', 'Growth', 'PPC'],
    featured: true,
    trending: true,
    agencies: [
      agency(1, 'Momentum Collective', 'Full-funnel growth marketing', 'London, UK', '2013', 4.9, 'Scaleups', ['Paid, SEO & CRO', 'Senior strategists', 'Transparent dashboards']),
      agency(2, 'Catalyst Media', 'Performance & paid media', 'Manchester, UK', '2014', 4.8, 'E-commerce', ['ROAS-focused', 'Google & Meta partners', 'Creative testing']),
      agency(3, 'Beacon & Bloom', 'Brand + demand generation', 'Bristol, UK', '2016', 4.8, 'B2B SaaS', ['Demand gen experts', 'ABM programmes', 'Pipeline reporting']),
      agency(4, 'Tidal Growth', 'Data-driven acquisition', 'Leeds, UK', '2015', 4.7, 'D2C Brands', ['Attribution modelling', 'Lifecycle marketing', 'Strong analytics']),
      agency(5, 'Hivemind', 'Social-first marketing', 'London, UK', '2017', 4.7, 'Consumer Brands', ['Creator partnerships', 'Short-form video', 'Community building']),
      agency(6, 'Ascend Digital', 'Lead generation specialists', 'Birmingham, UK', '2014', 4.6, 'Services & B2B', ['Cost-per-lead focus', 'Landing page CRO', 'CRM integration']),
      agency(7, 'Brightwave', 'Email & lifecycle', 'Edinburgh, UK', '2018', 4.6, 'Retention', ['Klaviyo experts', 'Automation flows', 'Retention strategy']),
      agency(8, 'Compass Marketing', 'Strategy-led marketing', 'Cardiff, UK', '2012', 4.5, 'SMEs', ['Fractional CMO', 'Marketing roadmaps', 'Hands-on support']),
      agency(9, 'Nova Reach', 'International campaigns', 'London, UK', '2016', 4.5, 'Global', ['Multi-market', 'Localisation', 'Media buying scale']),
      agency(10, 'Spark & Co', 'Marketing for startups', 'Remote, UK', '2019', 4.4, 'Early Stage', ['Flexible budgets', 'Rapid experiments', 'Founder-aligned']),
    ],
    body: intro('digital marketing', 'digital marketing agencies'),
  },
  {
    slug: 'best-pr-agencies',
    title: 'Top 10 Best PR Agencies in 2026',
    excerpt:
      'The public relations agencies earning standout coverage and building reputation — ranked by our editorial team.',
    category: 'services',
    author: 'eleanor-hughes',
    publishedAt: '2026-02-18',
    updatedAt: '2026-05-06',
    readingTime: 10,
    image: '/images/post-pr.webp',
    imageAlt: 'Press conference with journalists and microphones',
    tags: ['PR', 'Communications', 'Media', 'Reputation'],
    featured: true,
    agencies: [
      agency(1, 'Headline Communications', 'Earned media & reputation', 'London, UK', '2009', 4.9, 'Corporate & Tech', ['National & trade coverage', 'Crisis comms', 'Senior counsel']),
      agency(2, 'Bold Voice PR', 'Consumer & lifestyle PR', 'Manchester, UK', '2014', 4.8, 'Consumer Brands', ['Influencer relations', 'Product launches', 'Creative stunts']),
      agency(3, 'Northgate Affairs', 'Public affairs & policy', 'London, UK', '2011', 4.7, 'Public Affairs', ['Stakeholder engagement', 'Policy expertise', 'Reputation strategy']),
      agency(4, 'Lumen PR', 'Tech & startup PR', 'Cambridge, UK', '2016', 4.7, 'Startups & Tech', ['Founder profiling', 'Funding announcements', 'Tech press network']),
      agency(5, 'Verve Communications', 'B2B thought leadership', 'Bristol, UK', '2015', 4.6, 'B2B', ['Bylines & op-eds', 'Award entries', 'Speaker placement']),
      agency(6, 'Clearwater PR', 'Healthcare & science', 'Oxford, UK', '2013', 4.6, 'Healthcare', ['Regulated comms', 'Scientific storytelling', 'Media training']),
      agency(7, 'Storyline Agency', 'Brand storytelling', 'Leeds, UK', '2017', 4.5, 'Challenger Brands', ['Narrative strategy', 'Content + PR', 'Strong creative']),
      agency(8, 'Citadel Comms', 'Crisis & issues management', 'London, UK', '2010', 4.5, 'Crisis', ['24/7 response', 'Reputation defence', 'Experienced team']),
      agency(9, 'Greenroom PR', 'Sustainability & purpose', 'Brighton, UK', '2018', 4.4, 'Purpose Brands', ['ESG comms', 'Impact storytelling', 'Authentic campaigns']),
      agency(10, 'Pulse Media Relations', 'Affordable PR for SMEs', 'Remote, UK', '2019', 4.4, 'Small Business', ['Flexible retainers', 'Local & trade media', 'Hands-on support']),
    ],
    body: intro('PR', 'PR agencies'),
  },
  {
    slug: 'best-software-development-agencies',
    title: 'Top 10 Best Software Development Agencies in 2026',
    excerpt:
      'The software agencies shipping reliable web, mobile and product engineering — ranked for technical depth and delivery.',
    category: 'programming-tech',
    author: 'priya-nair',
    publishedAt: '2026-03-04',
    updatedAt: '2026-05-18',
    readingTime: 12,
    image: '/images/post-software.webp',
    imageAlt: 'Software engineers collaborating around code on screens',
    tags: ['Software', 'Engineering', 'Product', 'Development'],
    featured: true,
    trending: true,
    agencies: [
      agency(1, 'Cortex Labs', 'Product engineering at scale', 'London, UK', '2012', 4.9, 'Scaleups & Enterprise', ['Senior engineers', 'Cloud-native', 'Robust delivery process']),
      agency(2, 'Forge Digital', 'Web & platform development', 'Manchester, UK', '2014', 4.8, 'Web Platforms', ['Next.js & TypeScript', 'DevOps maturity', 'Strong QA']),
      agency(3, 'Beacon Software', 'Mobile app development', 'Bristol, UK', '2015', 4.8, 'Mobile', ['iOS & Android', 'React Native experts', 'App store track record']),
      agency(4, 'Quanta Build', 'AI & data products', 'Cambridge, UK', '2017', 4.7, 'AI & Data', ['ML engineering', 'Data pipelines', 'Strong research team']),
      agency(5, 'Atlas Engineering', 'Enterprise systems', 'London, UK', '2010', 4.7, 'Enterprise', ['Legacy modernisation', 'Integrations', 'Security-first']),
      agency(6, 'Northwind Dev', 'MVP & startup builds', 'Edinburgh, UK', '2018', 4.6, 'Startups', ['Fast MVPs', 'Founder-friendly', 'Lean process']),
      agency(7, 'Cobalt Code', 'Fintech engineering', 'London, UK', '2013', 4.6, 'Fintech', ['Compliance-aware', 'High reliability', 'Payments expertise']),
      agency(8, 'Maple Systems', 'Healthtech & regulated', 'Oxford, UK', '2015', 4.5, 'Healthtech', ['Regulated delivery', 'Interoperability', 'Robust testing']),
      agency(9, 'Driftcode', 'Design + engineering', 'Brighton, UK', '2016', 4.5, 'Product Design', ['Design-led builds', 'Tight feedback loops', 'Great UX']),
      agency(10, 'Relay Studio', 'Reliable dev partners', 'Remote, UK', '2019', 4.4, 'SMEs', ['Flexible teams', 'Clear communication', 'Maintenance plans']),
    ],
    body: intro('software development', 'software development agencies'),
  },
  {
    slug: 'best-ecommerce-seo-agencies',
    title: 'Top 8 Best E-commerce SEO Agencies in 2026',
    excerpt:
      'Specialist SEO agencies that grow organic revenue for online stores — ranked for product, category and technical expertise.',
    category: 'digital-marketing',
    author: 'marcus-bell',
    publishedAt: '2026-03-20',
    updatedAt: '2026-05-12',
    readingTime: 9,
    image: '/images/post-ecommerce-seo.webp',
    imageAlt: 'Online store analytics showing rising organic traffic',
    tags: ['SEO', 'E-commerce', 'Retail', 'Organic'],
    trending: true,
    agencies: [
      agency(1, 'Verdant Digital', 'E-commerce organic growth', 'Manchester, UK', '2016', 4.8, 'Retail', ['Category page strategy', 'Shopify & Magento', 'Revenue reporting']),
      agency(2, 'Orbit Media Lab', 'Programmatic product SEO', 'Cambridge, UK', '2017', 4.7, 'Marketplaces', ['Programmatic pages', 'Strong dev team', 'Scalable structure']),
      agency(3, 'Northbeam Search', 'Technical e-commerce SEO', 'London, UK', '2014', 4.7, 'Enterprise Retail', ['Crawl budget mastery', 'Faceted nav fixes', 'Migration experts']),
      agency(4, 'Summit SEO', 'Conversion-led store SEO', 'Birmingham, UK', '2013', 4.6, 'D2C', ['CRO + SEO', 'Clear KPIs', 'Senior-led']),
      agency(5, 'Linkforge', 'Retail digital PR', 'Bristol, UK', '2015', 4.6, 'Link Building', ['Product-led PR', 'Seasonal campaigns', 'Earned coverage']),
      agency(6, 'Apex Organic', 'Multi-location retail SEO', 'Leeds, UK', '2017', 4.5, 'Chains', ['Local + organic', 'Store locators', 'Scalable']),
      agency(7, 'Pinnacle Growth', 'Scaleup store SEO', 'Remote, UK', '2019', 4.4, 'Scaleups', ['Flexible retainers', 'Fast onboarding', 'Data-led']),
      agency(8, 'Evergreen Reach', 'Sustainable store SEO', 'Glasgow, UK', '2015', 4.4, 'SMEs', ['No long contracts', 'Education-first', 'Reliable comms']),
    ],
    body: intro('e-commerce SEO', 'e-commerce SEO agencies'),
  },
  {
    slug: 'best-ppc-agencies',
    title: 'Top 8 Best PPC Agencies in 2026',
    excerpt:
      'Paid search and social specialists that maximise return on ad spend — independently ranked for performance and transparency.',
    category: 'digital-marketing',
    author: 'marcus-bell',
    publishedAt: '2026-04-02',
    updatedAt: '2026-05-20',
    readingTime: 9,
    image: '/images/post-ppc.webp',
    imageAlt: 'Paid advertising dashboard with performance metrics',
    tags: ['PPC', 'Paid Media', 'Google Ads', 'Meta'],
    agencies: [
      agency(1, 'Catalyst Media', 'ROAS-focused paid media', 'Manchester, UK', '2014', 4.8, 'E-commerce', ['Google & Meta partners', 'Creative testing', 'Profit-focused']),
      agency(2, 'Momentum Collective', 'Full-funnel paid', 'London, UK', '2013', 4.8, 'Scaleups', ['Paid + CRO', 'Senior strategists', 'Transparent dashboards']),
      agency(3, 'Ascend Digital', 'Lead-gen PPC', 'Birmingham, UK', '2014', 4.6, 'B2B & Services', ['Cost-per-lead focus', 'Landing page CRO', 'CRM integration']),
      agency(4, 'Tidal Growth', 'Data-driven acquisition', 'Leeds, UK', '2015', 4.6, 'D2C', ['Attribution modelling', 'Strong analytics', 'Scaling expertise']),
      agency(5, 'Hivemind', 'Paid social specialists', 'London, UK', '2017', 4.5, 'Consumer', ['Creator-led ads', 'Short-form video', 'Community building']),
      agency(6, 'Nova Reach', 'International paid media', 'London, UK', '2016', 4.5, 'Global', ['Multi-market buying', 'Localisation', 'Media scale']),
      agency(7, 'Compass Marketing', 'Strategy-led PPC', 'Cardiff, UK', '2012', 4.4, 'SMEs', ['Fractional support', 'Roadmaps', 'Hands-on']),
      agency(8, 'Spark & Co', 'Startup paid media', 'Remote, UK', '2019', 4.4, 'Early Stage', ['Flexible budgets', 'Rapid experiments', 'Founder-aligned']),
    ],
    body: intro('PPC', 'PPC agencies'),
  },
  {
    slug: 'best-branding-agencies',
    title: 'Top 8 Best Branding Agencies in 2026',
    excerpt:
      'Strategic branding agencies that craft distinctive identities and brand systems — ranked for creativity and impact.',
    category: 'graphics-design',
    author: 'priya-nair',
    publishedAt: '2026-04-15',
    updatedAt: '2026-05-22',
    readingTime: 8,
    image: '/images/post-branding.webp',
    imageAlt: 'Brand identity materials including logos and colour palettes',
    tags: ['Branding', 'Identity', 'Strategy', 'Design'],
    agencies: [
      agency(1, 'Studio Meridian', 'Brand strategy & identity', 'London, UK', '2011', 4.9, 'Brand & Product', ['Award-winning', 'Strategy-led', 'Design systems']),
      agency(2, 'Kindling Creative', 'Startup branding', 'Brighton, UK', '2017', 4.7, 'Startups', ['Brand + web combined', 'Quick turnaround', 'Founder-friendly']),
      agency(3, 'Storyline Agency', 'Narrative-driven brands', 'Leeds, UK', '2017', 4.6, 'Challenger Brands', ['Brand storytelling', 'Verbal identity', 'Strong creative']),
      agency(4, 'Driftwood Studio', 'Lifestyle & hospitality', 'Cornwall, UK', '2015', 4.6, 'Hospitality', ['Visual identity', 'Photography network', 'Premium feel']),
      agency(5, 'Atlas Interactive', 'Enterprise rebrands', 'London, UK', '2010', 4.5, 'Enterprise', ['Large-scale rollouts', 'Brand guidelines', 'Global teams']),
      agency(6, 'Greenroom PR', 'Purpose-led brands', 'Brighton, UK', '2018', 4.5, 'Purpose Brands', ['Values-driven', 'Impact storytelling', 'Authentic']),
      agency(7, 'Cobalt & Co', 'SaaS brand systems', 'Cambridge, UK', '2016', 4.4, 'SaaS', ['Product branding', 'Figma-first', 'Scalable systems']),
      agency(8, 'Bramble Web', 'Small-business identity', 'Remote, UK', '2019', 4.3, 'Small Business', ['Affordable', 'Friendly process', 'Clear communication']),
    ],
    body: intro('branding', 'branding agencies'),
  },
  {
    slug: 'best-mobile-app-agencies',
    title: 'Top 8 Best Mobile App Development Agencies in 2026',
    excerpt:
      'The mobile specialists building polished iOS and Android apps — ranked for engineering quality and product thinking.',
    category: 'programming-tech',
    author: 'priya-nair',
    publishedAt: '2026-04-28',
    updatedAt: '2026-05-24',
    readingTime: 9,
    image: '/images/post-mobile.webp',
    imageAlt: 'Smartphones displaying mobile app interfaces',
    tags: ['Mobile', 'iOS', 'Android', 'Apps'],
    agencies: [
      agency(1, 'Beacon Software', 'iOS & Android apps', 'Bristol, UK', '2015', 4.8, 'Mobile', ['React Native experts', 'Native depth', 'App store track record']),
      agency(2, 'Cortex Labs', 'Product-grade mobile', 'London, UK', '2012', 4.8, 'Scaleups', ['Senior engineers', 'Robust delivery', 'Cloud backends']),
      agency(3, 'Driftcode', 'Design-led apps', 'Brighton, UK', '2016', 4.6, 'Product Design', ['Great UX', 'Tight feedback loops', 'Polished UI']),
      agency(4, 'Northwind Dev', 'MVP mobile builds', 'Edinburgh, UK', '2018', 4.6, 'Startups', ['Fast MVPs', 'Lean process', 'Founder-friendly']),
      agency(5, 'Cobalt Code', 'Fintech mobile', 'London, UK', '2013', 4.5, 'Fintech', ['Secure by design', 'Payments expertise', 'High reliability']),
      agency(6, 'Maple Systems', 'Healthtech mobile', 'Oxford, UK', '2015', 4.5, 'Healthtech', ['Regulated delivery', 'Robust testing', 'Interoperability']),
      agency(7, 'Forge Digital', 'Cross-platform builds', 'Manchester, UK', '2014', 4.4, 'Web + Mobile', ['Flutter & RN', 'Strong QA', 'DevOps maturity']),
      agency(8, 'Relay Studio', 'Reliable app partners', 'Remote, UK', '2019', 4.3, 'SMEs', ['Flexible teams', 'Maintenance plans', 'Clear comms']),
    ],
    body: intro('mobile app development', 'mobile app development agencies'),
  },
  {
    slug: 'best-content-marketing-agencies',
    title: 'Top 8 Best Content Marketing Agencies in 2026',
    excerpt:
      'Content agencies that build audiences and drive demand through editorial, SEO and creative — ranked by our editors.',
    category: 'digital-marketing',
    author: 'eleanor-hughes',
    publishedAt: '2026-05-08',
    updatedAt: '2026-05-26',
    readingTime: 8,
    image: '/images/post-content.webp',
    imageAlt: 'Editorial team planning a content calendar on a whiteboard',
    tags: ['Content', 'Editorial', 'SEO', 'Demand Gen'],
    agencies: [
      agency(1, 'Beacon & Bloom', 'Content + demand gen', 'Bristol, UK', '2016', 4.8, 'B2B SaaS', ['Editorial depth', 'Demand programmes', 'Pipeline focus']),
      agency(2, 'Verdant Digital', 'SEO content studio', 'Manchester, UK', '2016', 4.7, 'E-commerce', ['Topic clusters', 'Editorial team', 'Strong retail results']),
      agency(3, 'Storyline Agency', 'Brand storytelling', 'Leeds, UK', '2017', 4.6, 'Challenger Brands', ['Narrative strategy', 'Content + PR', 'Creative']),
      agency(4, 'Brightwave', 'Lifecycle content', 'Edinburgh, UK', '2018', 4.5, 'Retention', ['Email + content', 'Automation', 'Retention strategy']),
      agency(5, 'Momentum Collective', 'Full-funnel content', 'London, UK', '2013', 4.5, 'Scaleups', ['Content + paid', 'Senior strategists', 'Dashboards']),
      agency(6, 'Hivemind', 'Social content', 'London, UK', '2017', 4.4, 'Consumer', ['Short-form video', 'Creator network', 'Community']),
      agency(7, 'Compass Marketing', 'Strategy-led content', 'Cardiff, UK', '2012', 4.4, 'SMEs', ['Content roadmaps', 'Fractional support', 'Hands-on']),
      agency(8, 'Spark & Co', 'Startup content', 'Remote, UK', '2019', 4.3, 'Early Stage', ['Flexible scope', 'Rapid testing', 'Founder-aligned']),
    ],
    body: intro('content marketing', 'content marketing agencies'),
  },
]
